baseurl = "/"
relativeURLs = true
languageCode = "en-us"
title = "MM's Blog"
theme = "hugo-lithium"
googleAnalytics = "UA-102853974-2"
enableEmoji = true
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mmoench16"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/johnnyzeegerman"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown. You might find posts on subjects such as data analysis, programming (R, Java, Processing) and cycling."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "mm-home-logo.png"
    width = 50
    height = 50
    alt = "Logo"

